apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "kibble.name" . }}-secrets
  labels:
    app: {{ template "kibble.name" . }}
    chart: {{ template "kibble.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  ca_cert:
    {{ .Values.ca_cert | b64enc }}
  ca_key:
    {{ .Values.ca_key | b64enc }}
  dd_api_key:
    {{ .Values.dd_api_key | b64enc }}
