############################# Main targets #############################
all: clean build
########################################################################
build:
	@printf $(COLOR) "Building Kibble with OS: $(GOOS), ARCH: $(GOARCH)..."

